storage_options:
#    images_path: some path
#    books_path:  some path

loader_options:
    proxy_verifing_url: https://api.ipify.org?format=json
    proxies:
#        - proxy_server:port
    user_agents:
#        - user agent

    redirected_codes:
        - 301
        - 302
